hs = {}
hs.status = "Progressing"
hs.message = ""

local function contains (table, val)
  for i, v in ipairs(table) do
    if v == val then
      return true
    end
  end
  return false
end

if obj.status ~= nil then
  if obj.status.health ~= nil then
    hs.status = obj.status.health.status
    if obj.status.health.message ~= nil then
      hs.message = obj.status.health.message
    end
  end

  -- Check for transitional errors. There is no documentation of the condition types. I have encountered "InvalidSpecError", "ComparisonError" so far. 
  -- The rest are included based on information generated by ChatGPT
  if obj.status.conditions ~= nil then
    for i, condition in pairs(obj.status.conditions) do
      if contains({"InvalidSpecError", "ComparisonError", "SyncFailed", "ResourceNotFoundError","ClusterAccessError", "ForbiddenError","HelmTemplateFailed","AppProjectNotFound"}, condition.type) then
        hs.status = "Degraded"
        hs.message = condition.message
        return hs
      end
      
    end
  end

end
return hs
